language: java

sudo: false

 jdk:
	- oraclejdk8
	- oraclejdk7
  
addons:
  apt:
    packages:
		- oracle-java8-installer
	  
after_success:
	- bash <(curl -s https://codecov.io/bash)
  
branches:
  only:
	- master
	- java8-master